### ISSUE TITLE
Full Combo under "Recent" tab of profile not displaying correctly

### ISSUE THREAD

**Issue by Element118** [limjeck/osuplus#2]
Something is wrong with the "Recent" on the osu.ppy.sh profile page, for taiko and mania. It seems to be the full combo for the map, which still makes sense for taiko and mania, but now it is shown as a grey (nullx). Screenshot of bug included.

![osuplus_recentfcbug](https://cloud.githubusercontent.com/assets/8349060/15881151/55b88316-2d66-11e6-8942-aa6952b0581e.png)

**Comment by limjeck** [comment]
The nullx is now removed. No max combo for taiko/mania because of the API. Blame peppy.
