### ISSUE TITLE
UI: icons on beatmap

### ISSUE THREAD

**Issue by Devocub** [limjeck/osuplus#22]
Add icon-link to modding discussion here to match rest of site layout
![image](https://user-images.githubusercontent.com/2735824/67863298-b1b7e180-fb34-11e9-831a-58f7b67259d0.png)

site
![image](https://user-images.githubusercontent.com/2735824/67863337-c6947500-fb34-11e9-893f-325d90142bd8.png)

https://osu.ppy.sh/beatmapsets/%beatmapSetID%/discussion

**Comment by limjeck** [comment]
added
