### ISSUE TITLE
Mods column overriden by "Date" column

### ISSUE THREAD

**Issue by DWood46** [limjeck/osuplus#27]
It is not possible to see what mods are played on a map with the new added **Time** column on a beatmap page. The **Date** column overwrites the mods column when it is loaded. The setting to toggle the **Date** also no longer functions.

![chrome_2020-07-21_19-34-58](https://user-images.githubusercontent.com/6961830/88093123-7c06cd00-cb89-11ea-8ca8-789610453118.png)

**Comment by AadilRn** [comment]
Same happens to me. I'm not sure how this script is written but I prefer your date and time over ppy's so if it is possible to remove his to fix this that would be great.

**Comment by Explaiz** [comment]
Same problem

**Comment by limjeck** [comment]
Fixed (but you will have to get used to ppy's time)
