### ISSUE TITLE
Mods are not shown in the recent column

### ISSUE THREAD

**Issue by Sorgair** [limjeck/osuplus#28]
![image](https://user-images.githubusercontent.com/49007976/88243565-a4540180-cc45-11ea-8c77-04022dfaaa22.png)
i only play hd, and it's not showing here

also, i remember it happening all on this past sunday. in the morning i was checking someone's previous attempts and saw really suspicious modded scores, and then at night i checked again and none of the plays had mods...

**Comment by Sayac12** [comment]
#29

**Comment by limjeck** [comment]
Fixed
