### ISSUE TITLE
Feature request: Merge mod rankings to show more than the top 100

### ISSUE THREAD

**Issue by myangelaku** [limjeck/osuplus#31]
I'm not too sure on how osuplus shows mod rankings if an obligatory mod and a conditional mod are selected (Like, NF and NFSO for example), but if osuplus does API calls for each mod separately, I'd wish it would show more than just the top 100 scores on the map as it would help with potential research. 
![Screenshot_2020-09-04 The Quick Brown Fox - The Big Black (mapped by Blue Dragon)](https://user-images.githubusercontent.com/28674643/92222099-bfe63500-ee9e-11ea-84b8-123148097c8e.png)

**Comment by limjeck** [comment]
It fetches the top 100 scores for each mod combination, combines them and takes the top 100 among them. If it showed more than 100, it could be misleading in the sense that the #150 score may not be #150 among all NF/NFHD scores. If you want 100 NF and 100 NFHD scores you can still query for them separately.
