### ISSUE TITLE
Mods are still stacked on top of each other in recent scores

### ISSUE THREAD

**Issue by Magnus-Cosmos** [limjeck/osuplus#32]
![stacked recent scores](https://user-images.githubusercontent.com/39173355/96210907-f8b70680-0f40-11eb-9f2c-2b908882150b.PNG)
https://github.com/limjeck/osuplus/blob/ae39d537d3e3f7b1c52c76e74c02fe79b0f24334/osuplus.user.js#L2676-L2678
The div wrapper here seems unnecessary, removing it makes it work for me

**Comment by limjeck** [comment]
fixed
