### ISSUE TITLE
Country flags broken in beatmap leaderboards

### ISSUE THREAD

**Issue by Magnus-Cosmos** [limjeck/osuplus#35]
There were some recent changes to flags which breaks them for osuplus:
![image](https://user-images.githubusercontent.com/39173355/97470562-09db1c80-191e-11eb-96f1-89a7dab14654.png)
https://github.com/limjeck/osuplus/blob/3578e2e1390bb4303be74298cc32819da60ad4bd/osuplus.user.js#L3845-L3846
Changing the span to div fixes it for me (also `flag-country--scoreboard` and `flag-country--small-box` are no longer used, instead it should be `flag-country--flat`)

**Comment by limjeck** [comment]
fixed
