### ISSUE TITLE
Feature suggestion: An option that, once enabled, automatically redirects to the old site if possible

### ISSUE THREAD

**Issue by myangelaku** [limjeck/osuplus#36]
Examples:

- `https://osu.ppy.sh/beatmapsets/1249048#osu/2596015` => `https://old.ppy.sh/b/2596015`
- `https://osu.ppy.sh/beatmapsets/1249048` => `https://old.ppy.sh/s/1249048`
- `https://osu.ppy.sh/users/6506107` => `https://old.ppy.sh/u/6506107`

**Comment by limjeck** [comment]
Added back the site switcher thing
