### ISSUE TITLE
Leaderboard view issues

### ISSUE THREAD

**Issue by Zoomi96** [limjeck/osuplus#37]
A few days ago when I activated osu plus, this causes the leaderboards to change their appearance.

When osu plus is disabled it looks like this:
![image](https://user-images.githubusercontent.com/75452223/101089539-e76e9b80-357a-11eb-8d4f-0cdbd5f307de.png)

When osu plus is activated it looks like this
![image](https://user-images.githubusercontent.com/75452223/101089659-1553e000-357b-11eb-9966-d88da47c99b2.png)

**Comment by limjeck** [comment]
fixed
