### ISSUE TITLE
Beatmap is not defined in osu!preview

### ISSUE THREAD

**Issue by ohm002** [limjeck/osuplus#40]
the osu!preview is not working and the error in console is shown as
```
preview.js:5 Uncaught ReferenceError: Beatmap is not defined
    at new Preview (preview.js:5)
    at preview.html:110
```

**Comment by jmir1** [comment]
a lot of stuff should be fixed now with https://github.com/jmir1/osu-preview/commit/69def0e8e984f341b5b206c555dd79ae9f731c99

**Comment by limjeck** [comment]
Fixed. The issue was trying to put in the osu!preview before obtaining the beatmap id
