### ISSUE TITLE
Pin scores issue

### ISSUE THREAD

**Issue by Xulitol** [limjeck/osuplus#56]
![image](https://user-images.githubusercontent.com/62788409/151099368-5a91d1be-74f7-4f82-9ac9-b392ee114392.png)
This happens when you move your pinned scores.
I fixed this adding some conditions to code:
![image](https://user-images.githubusercontent.com/62788409/151099755-95f44054-5f45-4f7a-8a01-0caea58f0327.png)
Yeah, maybe there are another better solutions to fix this
Just count this as issue report

**Comment by limjeck** [comment]
Fixed
