### ISSUE TITLE
The twemoji country flag is too white on leaderboard when osu!plus enable

### ISSUE THREAD

**Issue by Kotoki1337** [limjeck/osuplus#60]
### Original:

![image](https://user-images.githubusercontent.com/35394151/159124969-37e2c5c0-a2c0-4ef8-b8cf-293b96865d74.png)

### osu!plus enabled:

![image](https://user-images.githubusercontent.com/35394151/159124982-430ca8d9-894f-4737-92bb-a84435886664.png)

### Compare:

![image](https://user-images.githubusercontent.com/35394151/159125011-50627683-d66c-4ec4-b8c8-b35a9714a3f2.png)![image](https://user-images.githubusercontent.com/35394151/159124988-5a96c3eb-6856-47fa-900e-c2b9c7058484.png)

Right one is osu!plus

**Comment by limjeck** [comment]
Nice catch. Fixed.
